# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings



try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in envelope_pb2_grpc.py depends on'
    )
