# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aios_sdk import envelope_pb2 as envelope__pb2
from aios_sdk import inference_pb2 as inference__pb2


try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in inference_pb2_grpc.py depends on'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunInference = channel.unary_unary(
                '/ai.os.inference.InferenceService/RunInference',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.BatchInference = channel.stream_stream(
                '/ai.os.inference.InferenceService/BatchInference',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.StreamInference = channel.unary_stream(
                '/ai.os.inference.InferenceService/StreamInference',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.StreamInferenceResponse.FromString,
                _registered_method=True)
        self.RunBatchInference = channel.unary_unary(
                '/ai.os.inference.InferenceService/RunBatchInference',
                request_serializer=inference__pb2.BatchInferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.BatchInferenceResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/ai.os.inference.InferenceService/GetModelInfo',
                request_serializer=envelope__pb2.StringValue.SerializeToString,
                response_deserializer=inference__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.ListAvailableModels = channel.unary_stream(
                '/ai.os.inference.InferenceService/ListAvailableModels',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=inference__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.UpdateModelStatus = channel.unary_unary(
                '/ai.os.inference.InferenceService/UpdateModelStatus',
                request_serializer=inference__pb2.ModelStatusUpdate.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai.os.inference.InferenceService/HealthCheck',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInference(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInference(self, request, context):
        """🎯 新增标准化接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBatchInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """🎯 新增模型管理接口
        model_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """🎯 新增健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInference,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceResponse.SerializeToString,
            ),
            'BatchInference': grpc.stream_stream_rpc_method_handler(
                    servicer.BatchInference,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceResponse.SerializeToString,
            ),
            'StreamInference': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.StreamInferenceResponse.SerializeToString,
            ),
            'RunBatchInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBatchInference,
                    request_deserializer=inference__pb2.BatchInferenceRequest.FromString,
                    response_serializer=inference__pb2.BatchInferenceResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=envelope__pb2.StringValue.FromString,
                    response_serializer=inference__pb2.ModelInfo.SerializeToString,
            ),
            'ListAvailableModels': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAvailableModels,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=inference__pb2.ModelInfo.SerializeToString,
            ),
            'UpdateModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelStatus,
                    request_deserializer=inference__pb2.ModelStatusUpdate.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.os.inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.os.inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.inference.InferenceService/RunInference',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai.os.inference.InferenceService/BatchInference',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.os.inference.InferenceService/StreamInference',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.StreamInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBatchInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.inference.InferenceService/RunBatchInference',
            inference__pb2.BatchInferenceRequest.SerializeToString,
            inference__pb2.BatchInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.inference.InferenceService/GetModelInfo',
            envelope__pb2.StringValue.SerializeToString,
            inference__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.os.inference.InferenceService/ListAvailableModels',
            envelope__pb2.Envelope.SerializeToString,
            inference__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.inference.InferenceService/UpdateModelStatus',
            inference__pb2.ModelStatusUpdate.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.inference.InferenceService/HealthCheck',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
