# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aios_sdk import envelope_pb2 as envelope__pb2
from aios_sdk import policy_pb2 as policy__pb2


try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in policy_pb2_grpc.py depends on'
    )


class PolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPolicy = channel.unary_unary(
                '/ai.os.policy.PolicyService/RegisterPolicy',
                request_serializer=policy__pb2.PolicyRule.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/ai.os.policy.PolicyService/Evaluate',
                request_serializer=policy__pb2.PolicyEvalRequest.SerializeToString,
                response_deserializer=policy__pb2.PolicyEvalResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/ai.os.policy.PolicyService/ListPolicies',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.BatchEvaluate = channel.unary_unary(
                '/ai.os.policy.PolicyService/BatchEvaluate',
                request_serializer=policy__pb2.BatchEvalRequest.SerializeToString,
                response_deserializer=policy__pb2.BatchEvalResponse.FromString,
                _registered_method=True)
        self.GetPolicyStats = channel.unary_unary(
                '/ai.os.policy.PolicyService/GetPolicyStats',
                request_serializer=policy__pb2.PolicyStatsRequest.SerializeToString,
                response_deserializer=policy__pb2.PolicyStats.FromString,
                _registered_method=True)
        self.CreatePolicyGroup = channel.unary_unary(
                '/ai.os.policy.PolicyService/CreatePolicyGroup',
                request_serializer=policy__pb2.PolicyGroup.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.EvaluateWithContext = channel.unary_unary(
                '/ai.os.policy.PolicyService/EvaluateWithContext',
                request_serializer=policy__pb2.EnhancedEvalRequest.SerializeToString,
                response_deserializer=policy__pb2.PolicyEvalResponse.FromString,
                _registered_method=True)
        self.UpdatePolicyStatus = channel.unary_unary(
                '/ai.os.policy.PolicyService/UpdatePolicyStatus',
                request_serializer=policy__pb2.PolicyStatusUpdate.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai.os.policy.PolicyService/HealthCheck',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEvaluate(self, request, context):
        """🎯 新增标准化接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicyGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateWithContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicyStatus(self, request, context):
        """🎯 新增管理接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPolicy,
                    request_deserializer=policy__pb2.PolicyRule.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=policy__pb2.PolicyEvalRequest.FromString,
                    response_serializer=policy__pb2.PolicyEvalResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'BatchEvaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEvaluate,
                    request_deserializer=policy__pb2.BatchEvalRequest.FromString,
                    response_serializer=policy__pb2.BatchEvalResponse.SerializeToString,
            ),
            'GetPolicyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyStats,
                    request_deserializer=policy__pb2.PolicyStatsRequest.FromString,
                    response_serializer=policy__pb2.PolicyStats.SerializeToString,
            ),
            'CreatePolicyGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicyGroup,
                    request_deserializer=policy__pb2.PolicyGroup.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'EvaluateWithContext': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateWithContext,
                    request_deserializer=policy__pb2.EnhancedEvalRequest.FromString,
                    response_serializer=policy__pb2.PolicyEvalResponse.SerializeToString,
            ),
            'UpdatePolicyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicyStatus,
                    request_deserializer=policy__pb2.PolicyStatusUpdate.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.os.policy.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.os.policy.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/RegisterPolicy',
            policy__pb2.PolicyRule.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/Evaluate',
            policy__pb2.PolicyEvalRequest.SerializeToString,
            policy__pb2.PolicyEvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/ListPolicies',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchEvaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/BatchEvaluate',
            policy__pb2.BatchEvalRequest.SerializeToString,
            policy__pb2.BatchEvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/GetPolicyStats',
            policy__pb2.PolicyStatsRequest.SerializeToString,
            policy__pb2.PolicyStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicyGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/CreatePolicyGroup',
            policy__pb2.PolicyGroup.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateWithContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/EvaluateWithContext',
            policy__pb2.EnhancedEvalRequest.SerializeToString,
            policy__pb2.PolicyEvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/UpdatePolicyStatus',
            policy__pb2.PolicyStatusUpdate.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.policy.PolicyService/HealthCheck',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
