# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aios_sdk import envelope_pb2 as envelope__pb2
from aios_sdk import prompt_pb2 as prompt__pb2


try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in prompt_pb2_grpc.py depends on'
    )


class PromptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTemplate = channel.unary_unary(
                '/ai.os.prompt.PromptService/RegisterTemplate',
                request_serializer=prompt__pb2.PromptTemplate.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.TestPrompt = channel.unary_unary(
                '/ai.os.prompt.PromptService/TestPrompt',
                request_serializer=prompt__pb2.TestPromptRequest.SerializeToString,
                response_deserializer=prompt__pb2.TestPromptResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/ai.os.prompt.PromptService/ListTemplates',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.BatchTestPrompt = channel.unary_unary(
                '/ai.os.prompt.PromptService/BatchTestPrompt',
                request_serializer=prompt__pb2.BatchTestRequest.SerializeToString,
                response_deserializer=prompt__pb2.BatchTestResponse.FromString,
                _registered_method=True)
        self.GetTemplateVersions = channel.unary_stream(
                '/ai.os.prompt.PromptService/GetTemplateVersions',
                request_serializer=envelope__pb2.StringValue.SerializeToString,
                response_deserializer=prompt__pb2.PromptVersion.FromString,
                _registered_method=True)
        self.CompareTemplates = channel.unary_unary(
                '/ai.os.prompt.PromptService/CompareTemplates',
                request_serializer=prompt__pb2.TemplateCompareRequest.SerializeToString,
                response_deserializer=prompt__pb2.TemplateCompareResponse.FromString,
                _registered_method=True)
        self.UpdateTemplateMetrics = channel.unary_unary(
                '/ai.os.prompt.PromptService/UpdateTemplateMetrics',
                request_serializer=prompt__pb2.PromptTemplate.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.SearchTemplates = channel.unary_stream(
                '/ai.os.prompt.PromptService/SearchTemplates',
                request_serializer=prompt__pb2.TemplateSearchRequest.SerializeToString,
                response_deserializer=prompt__pb2.PromptTemplate.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai.os.prompt.PromptService/HealthCheck',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)


class PromptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchTestPrompt(self, request, context):
        """🎯 新增标准化接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTemplateVersions(self, request, context):
        """template_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTemplateMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTemplates(self, request, context):
        """🎯 新增管理接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTemplate,
                    request_deserializer=prompt__pb2.PromptTemplate.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'TestPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.TestPrompt,
                    request_deserializer=prompt__pb2.TestPromptRequest.FromString,
                    response_serializer=prompt__pb2.TestPromptResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'BatchTestPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchTestPrompt,
                    request_deserializer=prompt__pb2.BatchTestRequest.FromString,
                    response_serializer=prompt__pb2.BatchTestResponse.SerializeToString,
            ),
            'GetTemplateVersions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTemplateVersions,
                    request_deserializer=envelope__pb2.StringValue.FromString,
                    response_serializer=prompt__pb2.PromptVersion.SerializeToString,
            ),
            'CompareTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareTemplates,
                    request_deserializer=prompt__pb2.TemplateCompareRequest.FromString,
                    response_serializer=prompt__pb2.TemplateCompareResponse.SerializeToString,
            ),
            'UpdateTemplateMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTemplateMetrics,
                    request_deserializer=prompt__pb2.PromptTemplate.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'SearchTemplates': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchTemplates,
                    request_deserializer=prompt__pb2.TemplateSearchRequest.FromString,
                    response_serializer=prompt__pb2.PromptTemplate.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.os.prompt.PromptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.os.prompt.PromptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/RegisterTemplate',
            prompt__pb2.PromptTemplate.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/TestPrompt',
            prompt__pb2.TestPromptRequest.SerializeToString,
            prompt__pb2.TestPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/ListTemplates',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchTestPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/BatchTestPrompt',
            prompt__pb2.BatchTestRequest.SerializeToString,
            prompt__pb2.BatchTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTemplateVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.os.prompt.PromptService/GetTemplateVersions',
            envelope__pb2.StringValue.SerializeToString,
            prompt__pb2.PromptVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/CompareTemplates',
            prompt__pb2.TemplateCompareRequest.SerializeToString,
            prompt__pb2.TemplateCompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTemplateMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/UpdateTemplateMetrics',
            prompt__pb2.PromptTemplate.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.os.prompt.PromptService/SearchTemplates',
            prompt__pb2.TemplateSearchRequest.SerializeToString,
            prompt__pb2.PromptTemplate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.prompt.PromptService/HealthCheck',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
