# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aios_sdk import envelope_pb2 as envelope__pb2
from aios_sdk import vector_pb2 as vector__pb2


try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in vector_pb2_grpc.py depends on'
    )


class VectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Write = channel.unary_unary(
                '/ai.os.vector.VectorService/Write',
                request_serializer=vector__pb2.WriteRequest.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.Search = channel.unary_stream(
                '/ai.os.vector.VectorService/Search',
                request_serializer=vector__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__pb2.SearchResult.FromString,
                _registered_method=True)
        self.Cluster = channel.unary_unary(
                '/ai.os.vector.VectorService/Cluster',
                request_serializer=vector__pb2.ClusterRequest.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.BatchOperation = channel.unary_unary(
                '/ai.os.vector.VectorService/BatchOperation',
                request_serializer=vector__pb2.BatchOperationRequest.SerializeToString,
                response_deserializer=vector__pb2.BatchOperationResponse.FromString,
                _registered_method=True)
        self.GetIndexStats = channel.unary_unary(
                '/ai.os.vector.VectorService/GetIndexStats',
                request_serializer=vector__pb2.IndexStatsRequest.SerializeToString,
                response_deserializer=vector__pb2.IndexStats.FromString,
                _registered_method=True)
        self.DeleteVectors = channel.unary_unary(
                '/ai.os.vector.VectorService/DeleteVectors',
                request_serializer=vector__pb2.DeleteRequest.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.UpdateVectorMetadata = channel.unary_unary(
                '/ai.os.vector.VectorService/UpdateVectorMetadata',
                request_serializer=vector__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai.os.vector.VectorService/HealthCheck',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.OptimizeIndex = channel.unary_unary(
                '/ai.os.vector.VectorService/OptimizeIndex',
                request_serializer=vector__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)


class VectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchOperation(self, request, context):
        """🎯 新增标准化接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVectorMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """🎯 新增管理接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=vector__pb2.WriteRequest.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vector__pb2.SearchRequest.FromString,
                    response_serializer=vector__pb2.SearchResult.SerializeToString,
            ),
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=vector__pb2.ClusterRequest.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'BatchOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchOperation,
                    request_deserializer=vector__pb2.BatchOperationRequest.FromString,
                    response_serializer=vector__pb2.BatchOperationResponse.SerializeToString,
            ),
            'GetIndexStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStats,
                    request_deserializer=vector__pb2.IndexStatsRequest.FromString,
                    response_serializer=vector__pb2.IndexStats.SerializeToString,
            ),
            'DeleteVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVectors,
                    request_deserializer=vector__pb2.DeleteRequest.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'UpdateVectorMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVectorMetadata,
                    request_deserializer=vector__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'OptimizeIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeIndex,
                    request_deserializer=vector__pb2.OptimizeRequest.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.os.vector.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.os.vector.VectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/Write',
            vector__pb2.WriteRequest.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.os.vector.VectorService/Search',
            vector__pb2.SearchRequest.SerializeToString,
            vector__pb2.SearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/Cluster',
            vector__pb2.ClusterRequest.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/BatchOperation',
            vector__pb2.BatchOperationRequest.SerializeToString,
            vector__pb2.BatchOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/GetIndexStats',
            vector__pb2.IndexStatsRequest.SerializeToString,
            vector__pb2.IndexStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/DeleteVectors',
            vector__pb2.DeleteRequest.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVectorMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/UpdateVectorMetadata',
            vector__pb2.UpdateMetadataRequest.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/HealthCheck',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizeIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.vector.VectorService/OptimizeIndex',
            vector__pb2.OptimizeRequest.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
