"""add_abac_attributes

Revision ID: 00d856588e17
Revises: 
Create Date: 2026-02-21 23:11:47.258549

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '00d856588e17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abac_policies',
    sa.Column('name', sa.String(length=200), nullable=False, comment='策略名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略详细描述'),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subject_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='主体属性条件 {roles, departments, levels, auth_levels, user_ids}'),
    sa.Column('resource_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='资源属性条件 {resource_types, sensitivities, owners, tags}'),
    sa.Column('environment_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='环境属性条件 {time_range, ip_whitelist, locations}'),
    sa.Column('actions', postgresql.ARRAY(sa.String(length=50)), nullable=False, comment='允许/拒绝的动作列表'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policy_active', 'abac_policies', ['is_active'], unique=False)
    op.create_index('idx_policy_effect', 'abac_policies', ['effect'], unique=False)
    op.create_index('idx_policy_priority', 'abac_policies', ['priority'], unique=False)
    op.create_index('idx_policy_resource', 'abac_policies', ['resource_conditions'], unique=False, postgresql_using='gin')
    op.create_index('idx_policy_subject', 'abac_policies', ['subject_conditions'], unique=False, postgresql_using='gin')
    op.create_table('feature_flags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('target_orgs', postgresql.ARRAY(sa.String(length=100)), nullable=True, comment='目标组织列表'),
    sa.Column('target_users', postgresql.ARRAY(sa.String(length=100)), nullable=True, comment='目标用户列表'),
    sa.Column('rollout_percentage', sa.Integer(), nullable=True, comment='灰度发布百分比 (0-100)'),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('name', 'id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policy_evaluation_logs',
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('subject_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('resource_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('matched_policies', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('deny_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policy_log_decision', 'policy_evaluation_logs', ['decision'], unique=False)
    op.create_index('idx_policy_log_time', 'policy_evaluation_logs', ['request_time'], unique=False)
    op.create_index(op.f('ix_policy_evaluation_logs_action'), 'policy_evaluation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_policy_evaluation_logs_resource_id'), 'policy_evaluation_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluation_logs_resource_type'), 'policy_evaluation_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_policy_evaluation_logs_subject_id'), 'policy_evaluation_logs', ['subject_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='配置值'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False, comment='是否敏感配置'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('key', 'id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_sub', sa.String(length=255), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('auth_level', sa.String(length=50), nullable=True),
    sa.Column('abac_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_abac', 'users', ['abac_attributes'], unique=False, postgresql_using='gin')
    op.create_index('idx_users_auth_level', 'users', ['auth_level'], unique=False)
    op.create_index('idx_users_department', 'users', ['department'], unique=False)
    op.create_index('idx_users_level', 'users', ['level'], unique=False)
    op.create_index('idx_users_oauth', 'users', ['oauth_provider', 'oauth_sub'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_level'), 'users', ['level'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('allowed_ips', postgresql.ARRAY(sa.String(length=45)), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='主体类型 (user, api_key, system)'),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求数据快照'),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='响应数据快照'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='操作状态'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('policy_decision', sa.String(length=10), nullable=True, comment='OPA 策略决策结果 (allow/deny)'),
    sa.Column('matched_policy_ids', postgresql.ARRAY(sa.String(length=100)), nullable=True, comment='匹配到的策略 ID 列表'),
    sa.Column('policy_evaluation_id', sa.UUID(), nullable=True, comment='关联的策略评估日志 ID'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_evaluation_id'], ['policy_evaluation_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_policy_decision', 'audit_logs', ['policy_decision'], unique=False)
    op.create_index('idx_audit_policy_eval', 'audit_logs', ['policy_evaluation_id'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_policy_evaluation_id'), 'audit_logs', ['policy_evaluation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitivity_default', sa.String(length=20), nullable=False),
    sa.Column('compliance_tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('allowed_locations', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('data_residency', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_compliance', 'organizations', ['compliance_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_org_sensitivity', 'organizations', ['sensitivity_default'], unique=False)
    op.create_index('idx_org_slug', 'organizations', ['slug'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('policy_assignments',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('extra_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['policy_id'], ['abac_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'target_type', 'target_id', name='uq_policy_assignment')
    )
    op.create_index('idx_assignment_target', 'policy_assignments', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_policy_assignments_policy_id'), 'policy_assignments', ['policy_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_member')
    )
    op.create_index('idx_org_member_org', 'organization_members', ['organization_id'], unique=False)
    op.create_index('idx_org_member_user', 'organization_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='项目标识符'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='项目配置'),
    sa.Column('sensitivity', sa.String(length=20), nullable=False, comment='资源敏感度 (public, internal, confidential, restricted)'),
    sa.Column('owner_id', sa.UUID(), nullable=True, comment="资源所有者（用于'仅所有者可访问'策略）"),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False, comment='资源标签，用于策略匹配'),
    sa.Column('classification', sa.String(length=50), nullable=True, comment='数据分类 (general, pii, financial, health)'),
    sa.Column('retention_days', sa.Integer(), nullable=True, comment='数据保留天数（合规要求）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_project_slug')
    )
    op.create_index('idx_project_org', 'projects', ['organization_id'], unique=False)
    op.create_index('idx_project_owner', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_project_sensitivity', 'projects', ['sensitivity'], unique=False)
    op.create_index('idx_project_tags', 'projects', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_sensitivity'), 'projects', ['sensitivity'], unique=False)
    op.create_table('agents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('workflow_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_engine', sa.String(length=50), nullable=True),
    sa.Column('enabled_tools', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('allowed_roles', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('requires_mfa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_agent_slug')
    )
    op.create_index('idx_agent_owner', 'agents', ['owner_id'], unique=False)
    op.create_index('idx_agent_project', 'agents', ['project_id'], unique=False)
    op.create_index('idx_agent_sensitivity', 'agents', ['sensitivity'], unique=False)
    op.create_index('idx_agent_status', 'agents', ['status'], unique=False)
    op.create_index('idx_agent_tags', 'agents', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_index(op.f('ix_agents_sensitivity'), 'agents', ['sensitivity'], unique=False)
    op.create_table('environments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='环境名称 (dev, staging, prod)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='环境变量（加密存储）'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='环境特定配置'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_env_project_name')
    )
    op.create_index('idx_env_project', 'environments', ['project_id'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_category', 'prompt_templates', ['category'], unique=False)
    op.create_index('idx_template_project', 'prompt_templates', ['project_id'], unique=False)
    op.create_index('idx_template_tags', 'prompt_templates', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_prompt_templates_project_id'), 'prompt_templates', ['project_id'], unique=False)
    op.create_table('quotas',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('limit', sa.BigInteger(), nullable=False),
    sa.Column('used', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('action_on_exceed', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_id', 'metric', 'period_start', name='uq_quota')
    )
    op.create_index('idx_quota_org', 'quotas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_quotas_organization_id'), 'quotas', ['organization_id'], unique=False)
    op.create_table('conversations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True, comment='会话标题'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='会话元数据'),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False, comment='资源敏感度'),
    sa.Column('owner_id', sa.UUID(), nullable=True, comment='会话所有者'),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False, comment='会话标签'),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False, comment='是否加密存储'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_owner', 'conversations', ['owner_id'], unique=False)
    op.create_index('idx_conversation_project', 'conversations', ['project_id'], unique=False)
    op.create_index('idx_conversation_sensitivity', 'conversations', ['sensitivity'], unique=False)
    op.create_index('idx_conversation_status', 'conversations', ['status'], unique=False)
    op.create_index('idx_conversation_user', 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_sensitivity'), 'conversations', ['sensitivity'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('integrations',
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='集成名称'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='提供商 (openai, anthropic, azure, etc.)'),
    sa.Column('integration_type', sa.String(length=50), nullable=False, comment='类型 (llm, vector_store, tool, webhook)'),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='认证凭证（加密存储）'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=True, comment='健康状态 (healthy, degraded, unhealthy)'),
    sa.Column('last_health_check', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integration_env', 'integrations', ['environment_id'], unique=False)
    op.create_index('idx_integration_provider', 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_environment_id'), 'integrations', ['environment_id'], unique=False)
    op.create_table('template_versions',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )
    op.create_index('idx_template_version', 'template_versions', ['template_id', 'version'], unique=False)
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    op.create_table('tools',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_type', sa.String(length=50), nullable=False),
    sa.Column('function_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_agent', 'tools', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tools_agent_id'), 'tools', ['agent_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_metric', 'usage_records', ['metric'], unique=False)
    op.create_index('idx_usage_org_period', 'usage_records', ['organization_id', 'period_start'], unique=False)
    op.create_index('idx_usage_project', 'usage_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_records_project_id'), 'usage_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('source_node', sa.String(length=100), nullable=False),
    sa.Column('target_node', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_edge_agent', 'workflow_edges', ['agent_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'node_id', name='uq_workflow_node')
    )
    op.create_index('idx_workflow_node_agent', 'workflow_nodes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_agent_id'), 'workflow_nodes', ['agent_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表'),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用记录'),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True, comment='关联的工具调用 ID'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Token 数量'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='响应延迟（毫秒）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_role', 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 (1-5)'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment='反馈类别'),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_conversation', 'feedbacks', ['conversation_id'], unique=False)
    op.create_index('idx_feedback_rating', 'feedbacks', ['rating'], unique=False)
    op.create_index(op.f('ix_feedbacks_conversation_id'), 'feedbacks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_message_id'), 'feedbacks', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_message_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_conversation_id'), table_name='feedbacks')
    op.drop_index('idx_feedback_rating', table_name='feedbacks')
    op.drop_index('idx_feedback_conversation', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_role', table_name='messages')
    op.drop_index('idx_message_created', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_workflow_nodes_agent_id'), table_name='workflow_nodes')
    op.drop_index('idx_workflow_node_agent', table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index('idx_workflow_edge_agent', table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_project_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_index('idx_usage_project', table_name='usage_records')
    op.drop_index('idx_usage_org_period', table_name='usage_records')
    op.drop_index('idx_usage_metric', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_tools_agent_id'), table_name='tools')
    op.drop_index('idx_tool_agent', table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_index('idx_template_version', table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_integrations_environment_id'), table_name='integrations')
    op.drop_index('idx_integration_provider', table_name='integrations')
    op.drop_index('idx_integration_env', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_sensitivity'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_index('idx_conversation_user', table_name='conversations')
    op.drop_index('idx_conversation_status', table_name='conversations')
    op.drop_index('idx_conversation_sensitivity', table_name='conversations')
    op.drop_index('idx_conversation_project', table_name='conversations')
    op.drop_index('idx_conversation_owner', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_quotas_organization_id'), table_name='quotas')
    op.drop_index('idx_quota_org', table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_prompt_templates_project_id'), table_name='prompt_templates')
    op.drop_index('idx_template_tags', table_name='prompt_templates', postgresql_using='gin')
    op.drop_index('idx_template_project', table_name='prompt_templates')
    op.drop_index('idx_template_category', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index('idx_env_project', table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_agents_sensitivity'), table_name='agents')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_index('idx_agent_tags', table_name='agents', postgresql_using='gin')
    op.drop_index('idx_agent_status', table_name='agents')
    op.drop_index('idx_agent_sensitivity', table_name='agents')
    op.drop_index('idx_agent_project', table_name='agents')
    op.drop_index('idx_agent_owner', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_projects_sensitivity'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index('idx_project_tags', table_name='projects', postgresql_using='gin')
    op.drop_index('idx_project_sensitivity', table_name='projects')
    op.drop_index('idx_project_owner', table_name='projects')
    op.drop_index('idx_project_org', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_org_member_user', table_name='organization_members')
    op.drop_index('idx_org_member_org', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_policy_assignments_policy_id'), table_name='policy_assignments')
    op.drop_index('idx_assignment_target', table_name='policy_assignments')
    op.drop_table('policy_assignments')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index('idx_org_slug', table_name='organizations')
    op.drop_index('idx_org_sensitivity', table_name='organizations')
    op.drop_index('idx_org_compliance', table_name='organizations', postgresql_using='gin')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_policy_evaluation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_policy_eval', table_name='audit_logs')
    op.drop_index('idx_audit_policy_decision', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index('idx_api_key_prefix', table_name='api_keys')
    op.drop_index('idx_api_key_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_level'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_oauth', table_name='users')
    op.drop_index('idx_users_level', table_name='users')
    op.drop_index('idx_users_department', table_name='users')
    op.drop_index('idx_users_auth_level', table_name='users')
    op.drop_index('idx_users_abac', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_policy_evaluation_logs_subject_id'), table_name='policy_evaluation_logs')
    op.drop_index(op.f('ix_policy_evaluation_logs_resource_type'), table_name='policy_evaluation_logs')
    op.drop_index(op.f('ix_policy_evaluation_logs_resource_id'), table_name='policy_evaluation_logs')
    op.drop_index(op.f('ix_policy_evaluation_logs_action'), table_name='policy_evaluation_logs')
    op.drop_index('idx_policy_log_time', table_name='policy_evaluation_logs')
    op.drop_index('idx_policy_log_decision', table_name='policy_evaluation_logs')
    op.drop_table('policy_evaluation_logs')
    op.drop_table('feature_flags')
    op.drop_index('idx_policy_subject', table_name='abac_policies', postgresql_using='gin')
    op.drop_index('idx_policy_resource', table_name='abac_policies', postgresql_using='gin')
    op.drop_index('idx_policy_priority', table_name='abac_policies')
    op.drop_index('idx_policy_effect', table_name='abac_policies')
    op.drop_index('idx_policy_active', table_name='abac_policies')
    op.drop_table('abac_policies')
    # ### end Alembic commands ###
