# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import envelope_pb2 as envelope__pb2
from . import langgraph_pb2 as langgraph__pb2


try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in langgraph_pb2_grpc.py depends on'
    )


class LangGraphRouterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoutingDecision = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/GetRoutingDecision',
                request_serializer=langgraph__pb2.RoutingRequest.SerializeToString,
                response_deserializer=langgraph__pb2.RoutingResponse.FromString,
                _registered_method=True)
        self.StreamRoutingDecision = channel.stream_stream(
                '/ai.os.langgraph.LangGraphRouter/StreamRoutingDecision',
                request_serializer=langgraph__pb2.RoutingRequest.SerializeToString,
                response_deserializer=langgraph__pb2.RoutingResponse.FromString,
                _registered_method=True)
        self.GetRoutingStats = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/GetRoutingStats',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=langgraph__pb2.RoutingStats.FromString,
                _registered_method=True)
        self.UpdateRoutingStrategy = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/UpdateRoutingStrategy',
                request_serializer=langgraph__pb2.RoutingStrategyUpdate.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.GetAgentRoutingConfig = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/GetAgentRoutingConfig',
                request_serializer=envelope__pb2.StringValue.SerializeToString,
                response_deserializer=langgraph__pb2.AgentRoutingConfig.FromString,
                _registered_method=True)
        self.UpdateAgentRoutingConfig = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/UpdateAgentRoutingConfig',
                request_serializer=langgraph__pb2.AgentRoutingConfig.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.BatchRouting = channel.stream_stream(
                '/ai.os.langgraph.LangGraphRouter/BatchRouting',
                request_serializer=langgraph__pb2.RoutingRequest.SerializeToString,
                response_deserializer=langgraph__pb2.RoutingResponse.FromString,
                _registered_method=True)
        self.ValidateRouting = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/ValidateRouting',
                request_serializer=langgraph__pb2.RoutingRequest.SerializeToString,
                response_deserializer=langgraph__pb2.RoutingResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai.os.langgraph.LangGraphRouter/HealthCheck',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)


class LangGraphRouterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRoutingDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRoutingDecision(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutingStats(self, request, context):
        """🎯 新增标准化接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoutingStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentRoutingConfig(self, request, context):
        """agent_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgentRoutingConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRouting(self, request_iterator, context):
        """🎯 新增批量路由
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateRouting(self, request, context):
        """🎯 新增验证接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """🎯 新增健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangGraphRouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoutingDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingDecision,
                    request_deserializer=langgraph__pb2.RoutingRequest.FromString,
                    response_serializer=langgraph__pb2.RoutingResponse.SerializeToString,
            ),
            'StreamRoutingDecision': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRoutingDecision,
                    request_deserializer=langgraph__pb2.RoutingRequest.FromString,
                    response_serializer=langgraph__pb2.RoutingResponse.SerializeToString,
            ),
            'GetRoutingStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingStats,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=langgraph__pb2.RoutingStats.SerializeToString,
            ),
            'UpdateRoutingStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoutingStrategy,
                    request_deserializer=langgraph__pb2.RoutingStrategyUpdate.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'GetAgentRoutingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentRoutingConfig,
                    request_deserializer=envelope__pb2.StringValue.FromString,
                    response_serializer=langgraph__pb2.AgentRoutingConfig.SerializeToString,
            ),
            'UpdateAgentRoutingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentRoutingConfig,
                    request_deserializer=langgraph__pb2.AgentRoutingConfig.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'BatchRouting': grpc.stream_stream_rpc_method_handler(
                    servicer.BatchRouting,
                    request_deserializer=langgraph__pb2.RoutingRequest.FromString,
                    response_serializer=langgraph__pb2.RoutingResponse.SerializeToString,
            ),
            'ValidateRouting': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateRouting,
                    request_deserializer=langgraph__pb2.RoutingRequest.FromString,
                    response_serializer=langgraph__pb2.RoutingResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.os.langgraph.LangGraphRouter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.os.langgraph.LangGraphRouter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LangGraphRouter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRoutingDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/GetRoutingDecision',
            langgraph__pb2.RoutingRequest.SerializeToString,
            langgraph__pb2.RoutingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRoutingDecision(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai.os.langgraph.LangGraphRouter/StreamRoutingDecision',
            langgraph__pb2.RoutingRequest.SerializeToString,
            langgraph__pb2.RoutingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutingStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/GetRoutingStats',
            envelope__pb2.Envelope.SerializeToString,
            langgraph__pb2.RoutingStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoutingStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/UpdateRoutingStrategy',
            langgraph__pb2.RoutingStrategyUpdate.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentRoutingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/GetAgentRoutingConfig',
            envelope__pb2.StringValue.SerializeToString,
            langgraph__pb2.AgentRoutingConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgentRoutingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/UpdateAgentRoutingConfig',
            langgraph__pb2.AgentRoutingConfig.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRouting(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai.os.langgraph.LangGraphRouter/BatchRouting',
            langgraph__pb2.RoutingRequest.SerializeToString,
            langgraph__pb2.RoutingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateRouting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/ValidateRouting',
            langgraph__pb2.RoutingRequest.SerializeToString,
            langgraph__pb2.RoutingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.langgraph.LangGraphRouter/HealthCheck',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
