# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import envelope_pb2 as envelope__pb2
from . import model_pb2 as model__pb2


try:
    from grpc._utilities import first_version_is_lower
except ImportError:

    raise RuntimeError(
        + f' but the generated code in model_pb2_grpc.py depends on'
    )


class ModelRegistryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/RegisterModel',
                request_serializer=model__pb2.ModelRegistration.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/ListModels',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.PublishLifecycleEvent = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/PublishLifecycleEvent',
                request_serializer=model__pb2.ModelLifecycleEvent.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/GetModelStatus',
                request_serializer=envelope__pb2.StringValue.SerializeToString,
                response_deserializer=model__pb2.ModelStatus.FromString,
                _registered_method=True)
        self.GetModelStats = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/GetModelStats',
                request_serializer=model__pb2.ModelStatsRequest.SerializeToString,
                response_deserializer=model__pb2.ModelStats.FromString,
                _registered_method=True)
        self.QueryModels = channel.unary_stream(
                '/ai.os.model.ModelRegistryService/QueryModels',
                request_serializer=model__pb2.ModelQueryRequest.SerializeToString,
                response_deserializer=model__pb2.ModelRegistration.FromString,
                _registered_method=True)
        self.UpdateModelStatus = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/UpdateModelStatus',
                request_serializer=model__pb2.ModelStatusUpdate.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.ScaleModel = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/ScaleModel',
                request_serializer=model__pb2.ScaleRequest.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai.os.model.ModelRegistryService/HealthCheck',
                request_serializer=envelope__pb2.Envelope.SerializeToString,
                response_deserializer=envelope__pb2.Envelope.FromString,
                _registered_method=True)


class ModelRegistryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishLifecycleEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """🎯 新增标准化接口
        model_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScaleModel(self, request, context):
        """🎯 新增管理接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=model__pb2.ModelRegistration.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'PublishLifecycleEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishLifecycleEvent,
                    request_deserializer=model__pb2.ModelLifecycleEvent.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=envelope__pb2.StringValue.FromString,
                    response_serializer=model__pb2.ModelStatus.SerializeToString,
            ),
            'GetModelStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStats,
                    request_deserializer=model__pb2.ModelStatsRequest.FromString,
                    response_serializer=model__pb2.ModelStats.SerializeToString,
            ),
            'QueryModels': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryModels,
                    request_deserializer=model__pb2.ModelQueryRequest.FromString,
                    response_serializer=model__pb2.ModelRegistration.SerializeToString,
            ),
            'UpdateModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelStatus,
                    request_deserializer=model__pb2.ModelStatusUpdate.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'ScaleModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ScaleModel,
                    request_deserializer=model__pb2.ScaleRequest.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=envelope__pb2.Envelope.FromString,
                    response_serializer=envelope__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.os.model.ModelRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.os.model.ModelRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelRegistryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/RegisterModel',
            model__pb2.ModelRegistration.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/ListModels',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishLifecycleEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/PublishLifecycleEvent',
            model__pb2.ModelLifecycleEvent.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/GetModelStatus',
            envelope__pb2.StringValue.SerializeToString,
            model__pb2.ModelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/GetModelStats',
            model__pb2.ModelStatsRequest.SerializeToString,
            model__pb2.ModelStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.os.model.ModelRegistryService/QueryModels',
            model__pb2.ModelQueryRequest.SerializeToString,
            model__pb2.ModelRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/UpdateModelStatus',
            model__pb2.ModelStatusUpdate.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScaleModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/ScaleModel',
            model__pb2.ScaleRequest.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.os.model.ModelRegistryService/HealthCheck',
            envelope__pb2.Envelope.SerializeToString,
            envelope__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
